name: hybrid_cli
description: A CLI tool for generating Flutter code with clean architecture structure
version: 1.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  io: ^1.0.4
  xml: 6.5.0
  xcode_parser: ^1.2.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  hybrid: main
